name: copy-datadog-service-catalog-provider

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:




  update-DD-service-catalog:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
        
      - id: dd-overall-data
        name: Getting service data from service.datadog.yaml
        uses: mikefarah/yq@master 
        with:
          cmd: yq 'map_values(.)' 'service.datadog.yaml'   

      - name: Check if dd-service output is working
        run: yq '.dd-service' 'service.datadog.yaml'
      
      - name: Check if dd-service output is working
        run: echo "${{ steps.dd-overall-data.outputs.result.dd-service }}"

      # - name: Set env variables for each service catalog 
      #   shell: bash
      #   run: |
      #     for line in "${{ steps.dd-overall-data.outputs.result }}"
      #     do
      #       echo $line
      #       echo "----"
      #     done

      # - uses: arcxp/datadog-service-catalog-metadata-provider@v2
      #   name: Update datadog service catalog metadata with new metadata
      #   with:
      #     schema-version: v2.1
      #     datadog-hostname: api.us5.datadoghq.com
      #     datadog-key: ${{ secrets.DATADOG_API_KEY }}
      #     datadog-app-key: ${{ secrets.DATADOG_APP_KEY }}

      #     service-name: ${{ steps.dd-service.outputs.result }}
      #     team: ${{ steps.dd-team.outputs.result }}
      #     application: ${{ steps.dd-application.outputs.result}}
      #     description: ${{ steps.dd-description.outputs.result }}
      #     lifecycle: ${{ steps.dd-lifecycle.outputs.result }}
      #     tier: ${{ steps.dd-tier.outputs.result }}
      #     email: ${{ steps.dd-contacts-email.outputs.result }}
      #     slack-support-channel: ${{ steps.dd-contacts-slack.outputs.result }}

      #     contacts: |
      #       ${{ steps.service-datadog-yaml.outputs.result.contacts }}

      #     links: |
      #       ${{ steps.dd-links.outputs.result }}
            
      #     integrations: |
      #       ${{ steps.dd-integrations.outputs.result }}
          