name: datadog-service-catalog-provider

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  update-DD-service-catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
        
      - id: dd-service
        name: Getting service data from service.datadog.yaml
        uses: mikefarah/yq@master 
        with:
          cmd: yq '.dd-service' 'service.datadog.yaml'
      - id: dd-team 
        run: yq '.team' 'service.datadog.yaml'
      - id: dd-application 
        run: yq '.application' 'service.datadog.yaml'
      - id: dd-description 
        run: yq '.description' 'service.datadog.yaml'
      - id: dd-lifecycle 
        run: yq '.lifecycle' 'service.datadog.yaml'
      - id: dd-tier 
        run: yq '.tier' 'service.datadog.yaml'       
      - id: dd-contacts-email 
        run: yq '.contacts.[1].contact' 'service.datadog.yaml'
      - id: dd-contacts-slack 
        run: yq '.contacts.[0].contact' 'service.datadog.yaml'   
      - id: dd-links 
        run: yq '.links' 'service.datadog.yaml'
      - id: dd-integrations 
        run: yq '.integrations.pagerduty.service-url' 'service.datadog.yaml'            

      - name: Check if dd-service output is working
        run: echo "${{ steps.dd-service.outputs.result }}"
      - name: Check if dd-team output is working
        run: echo '${{ steps.dd-team.outputs.result }}'
      - name: Check if dd-application output is working
        run: echo '${{ steps.dd-application.outputs.result}}'
      - name: Check if dd-description output is working
        run: echo "${{ steps.dd-description.outputs.result }}"
      - name: Check if dd-lifecycle output is working
        run: echo "${{ steps.dd-lifecycle.outputs.result }}"
      - name: Check if dd-tier output is working
        run: echo "${{ steps.dd-tier.outputs.result }}"

      - name: Check if dd-contacts-slack output is working
        run: echo "${{ steps.dd-contacts-slack.outputs.result }}" 
      - name: Check if dd-contacts-email is working
        run: echo "${{ steps.dd-contacts-email.outputs.result }}" 

      - name: Check if dd-links output is working
        run: echo "${{ steps.dd-links.outputs.result }}"
        
      - name: Check if dd-integrations output is working
        run: echo "${{ steps.dd-integrations.outputs.result }}"


      # - uses: arcxp/datadog-service-catalog-metadata-provider@v2
      #   with:
      #     schema-version: v2.1
      #     datadog-hostname: api.us5.datadoghq.com
      #     datadog-key: ${{ secrets.DATADOG_API_KEY }}
      #     datadog-app-key: ${{ secrets.DATADOG_APP_KEY }}

      #     service-name: ${{ steps.dd-service.outputs.result }}
      #     team: ${{ steps.dd-team.outputs.result }}
      #     application: ${{ steps.dd-application.outputs.result}}
      #     description: ${{ steps.dd-description.outputs.result }}
      #     lifecycle: ${{ steps.dd-lifecycle.outputs.result }}
      #     tier: ${{ steps.dd-tier.outputs.result }}
      #     email: ${{ steps.dd-contacts-email.outputs.result }}
      #     slack-support-channel: ${{ steps.dd-contacts-slack.outputs.result }}

      #     contacts: |
      #       ${{ steps.service-datadog-yaml.outputs.result.contacts }}

      #     links: |
      #       ${{ steps.dd-links.outputs.result }}
            
      #     integrations: |
      #       ${{ steps.dd-integrations.outputs.result }}
          