name: datadog-service-catalog-provider

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  update-DD-service-catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
        
      - name: Get yq github action to read service.datadog.yaml
        uses: mikefarah/yq@master 
      - name: Set service data env variables
        run: |
          echo "dd-service=$(yq '.dd-service' 'service.datadog.yaml')" >> $GITHUB_ENV
          echo "dd-team=$(yq '.team' 'service.datadog.yaml')" >> $GITHUB_ENV
          echo "dd-application=$(yq '.application' 'service.datadog.yaml')" >> $GITHUB_ENV
          echo "dd-team=$(yq '.team' 'service.datadog.yaml')" >> $GITHUB_ENV
          echo "dd-application=$(yq '.application' 'service.datadog.yaml')" >> $GITHUB_ENV
          echo "dd-description=$(yq '.description' 'service.datadog.yaml')" >> $GITHUB_ENV
          echo "dd-lifecycle=$(yq '.lifecycle' 'service.datadog.yaml')" >> $GITHUB_ENV
          echo "dd-tier=$(yq '.tier' 'service.datadog.yaml')" >> $GITHUB_ENV
          echo "dd-contacts-email=$(yq '.contacts.[1].contact' 'service.datadog.yaml')" >> $GITHUB_ENV
          echo "dd-contacts-slack=$(yq '.contacts.[0].contact' 'service.datadog.yaml')" >> $GITHUB_ENV
          echo "dd-links="$(yq '.links' 'service.datadog.yaml')"" >> $GITHUB_ENV
          echo "dd-integrations="$(yq '.integrations.pagerduty.service-url' 'service.datadog.yaml')"" >> $GITHUB_ENV          

      - name: Check if dd-service output is working
        run: echo "${{ env.dd-service }}"
      - name: Check if dd-team output is working
        run: echo '${{ env.dd-team }}'
      - name: Check if dd-application output is working
        run: echo '${{ env.dd-application }}'
      - name: Check if dd-description output is working
        run: echo "${{ env.dd-description }}"
      - name: Check if dd-lifecycle output is working
        run: echo "${{ env.dd-lifecycle }}"
      - name: Check if dd-tier output is working
        run: echo "${{ env.dd-tier }}"

      - name: Check if dd-contacts-slack output is working
        run: echo "${{ env.dd-contacts-email }}" 
      - name: Check if dd-contacts-email is working
        run: echo "${{ env.dd-contacts-slack }}" 

      - name: Check if dd-links output is working
        run: echo "${{ env.dd-links}}"
        
      - name: Check if dd-integrations output is working
        run: echo "${{ env.dd-integrations }}"


      # - uses: arcxp/datadog-service-catalog-metadata-provider@v2
      #   with:
      #     schema-version: v2.1
      #     datadog-hostname: api.us5.datadoghq.com
      #     datadog-key: ${{ secrets.DATADOG_API_KEY }}
      #     datadog-app-key: ${{ secrets.DATADOG_APP_KEY }}

      #     service-name: ${{ steps.dd-service.outputs.result }}
      #     team: ${{ steps.dd-team.outputs.result }}
      #     application: ${{ steps.dd-application.outputs.result}}
      #     description: ${{ steps.dd-description.outputs.result }}
      #     lifecycle: ${{ steps.dd-lifecycle.outputs.result }}
      #     tier: ${{ steps.dd-tier.outputs.result }}
      #     email: ${{ steps.dd-contacts-email.outputs.result }}
      #     slack-support-channel: ${{ steps.dd-contacts-slack.outputs.result }}

      #     contacts: |
      #       ${{ steps.service-datadog-yaml.outputs.result.contacts }}

      #     links: |
      #       ${{ steps.dd-links.outputs.result }}
            
      #     integrations: |
      #       ${{ steps.dd-integrations.outputs.result }}
          