name: datadog-service-catalog-provider

on:
  workflow_call:
    secrets:
      dd_api_key:
        description: 'A Datadog API key'
        required: true
      dd_app_key:
        description: 'A Datadog app key'
        required: true

jobs:
  # Checks if any service.datadog.yaml exists and was edited -> puts all of their paths into an arr -> output for next job in "list_of_service_datadog_files"
  check_for_service_datadog_yaml_files_changed:
    runs-on: ubuntu-latest
    #Output defined by bash script below. Getting list of service.datadog.yaml filepaths that were modified, in JSON array format ["filepath1", "filepath2", ...] 
    outputs:
      list_of_service_datadog_files: ${{ steps.get_service_files.outputs.filepaths }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files across repo
        id: changed_files
        uses: tj-actions/changed-files@v42.0.4

      - name: Check for service.datadog.yaml files changed. Then run update-datadog-service-catalog action
        id: get_service_files
        run: |
          changedFilesArr=(${{steps.changed_files.outputs.all_changed_files}})
          outputVal="["
          i=0
          for filepath in ${changedFilesArr[@]}; do
            if [[ $filepath == *"service.datadog.yaml" ]]; then
              if [[ $i -eq 0 ]]; then
                outputVal+="\"./$filepath\""
              else
                outputVal+=", \"./$filepath\""
              fi
              i=$(( i + 1 ))
            fi
          done
          outputVal+="]"
          echo "$outputVal"
          echo "filepaths=$outputVal" >> "$GITHUB_OUTPUT"

  look_for_multiple_files_in_single_yaml:
    if: needs.check_for_service_datadog_yaml_files_changed.outputs.list_of_service_datadog_files != '[]'
    needs: check_for_service_datadog_yaml_files_changed
    strategy:
      #Get list of service.datadog.yaml files from output in job above.
      matrix:
        paths: ${{ fromJSON(needs.check_for_service_datadog_yaml_files_changed.outputs.list_of_service_datadog_files) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4.1.1

      - name: Split multi yaml files
        id: multi_yaml_split_vals
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -s '"file_" + $index' ${{ matrix.paths }}
            ls
      
      - name: Check if output works
        run: |
          echo "${{ steps.multi_yaml_split_vals.outputs.results }}"
          echo "${{ steps.multi_yaml_split_vals.outputs }}"
  
  # update_datadog_service_catalog_with_matrix_values:
  #   if: needs.check_for_service_datadog_yaml_files_changed.outputs.list_of_service_datadog_files != '[]'
  #   needs: check_for_service_datadog_yaml_files_changed
  #   strategy:
  #     #Get list of service.datadog.yaml files from output in job above.
  #     matrix:
  #       paths: ${{ fromJSON(needs.check_for_service_datadog_yaml_files_changed.outputs.list_of_service_datadog_files) }}
  #   #Call the update-datadog-service-catalog action on each "path"(service.datadog.yaml file) found.
  #   uses: ./.github/workflows/update-datadog-service-catalog.yaml
  #   secrets: inherit
  #   with:
  #     matrix_path: ${{ matrix.paths }}