name: datadog-service-catalog-provider

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
        
      - id: dd-service
        name: Getting service data from service.datadog.yaml
        uses: mikefarah/yq@master 
        with:
          cmd: yq '.dd-service' 'service.datadog.yaml'
      - id: dd-team
        uses: mikefarah/yq@master 
        with:
          cmd: yq '.team' 'service.datadog.yaml'
      - id: dd-application
        uses: mikefarah/yq@master 
        with:
          cmd: yq '.application' 'service.datadog.yaml'
      - id: dd-description
        uses: mikefarah/yq@master 
        with:
          cmd: yq '.description' 'service.datadog.yaml'
      - id: dd-lifecycle
        uses: mikefarah/yq@master 
        with:
          cmd: yq '.lifecycle' 'service.datadog.yaml'
      - id: dd-tier
        uses: mikefarah/yq@master 
        with:
          cmd: yq '.tier' 'service.datadog.yaml'

          
      - id: dd-contacts
        uses: mikefarah/yq@master 
        with:
          cmd: yq '.contacts' 'service.datadog.yaml'   
      - id: dd-links
        uses: mikefarah/yq@master 
        with:
          cmd: yq '.links' 'service.datadog.yaml'           

      - name: Check if dd-service output is working
        run: echo "${{ steps.dd-service.outputs.result }}"
      
      - name: Checking if its running correctly
        run: echo '${{ steps.dd-team.outputs.result }}'

      - name: Checking if its running correctly 2
        run: echo '${{ steps.dd-application.outputs.result}}'

      - name: Checking if its running correctly 3
        run: echo "${{ steps.dd-contacts.outputs.result }}"





      # - uses: arcxp/datadog-service-catalog-metadata-provider@v2
      #   with:
      #     schema-version: v2.1
      #     datadog-hostname: api.us5.datadoghq.com
      #     datadog-key: ${{ secrets.DATADOG_API_KEY }}
      #     datadog-app-key: ${{ secrets.DATADOG_APP_KEY }}

      #     service-name: ${{ steps.service-datadog-yaml.outputs.result.dd-service }}
      #     team: ${{ steps.service-datadog-yaml.outputs.result.team }}
      #     application: ${{ steps.service-datadog-yaml.outputs.result.application }}
      #     description: ${{ steps.service-datadog-yaml.outputs.result.description }}
      #     lifecycle: ${{ steps.service-datadog-yaml.outputs.result.lifecycle }}
      #     tier: ${{ steps.service-datadog-yaml.outputs.result.tier }}
      #     email: ${{ steps.service-datadog-yaml.outputs.result.contacts.email.contact }}
      #     slack-support-channel: ${{ steps.service-datadog-yaml.outputs.result.contacts.slack.contact }}

      #     links: |
      #       ${{ steps.service-datadog-yaml.outputs.result.links }}
            
      #     integrations: |
      #       ${{ steps.service-datadog-yaml.outputs.result.integrations }}
          
      #     contacts: |
      #       ${{ steps.service-datadog-yaml.outputs.result.contacts }}