name: datadog-service-catalog-caller

on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    call_reusable_workflow_datadog_service_catalog_provider:
        uses: ./.github/workflows/datadog-service-catalog-provider.yaml
        secrets:
            dd_api_key: ${{ secrets.DATADOG_API_KEY }}
            dd_app_key: ${{ secrets.DATADOG_APP_KEY }}